INSERT INTO AGENDA (COMPROMISSO, DATE, TIME, LOCAL) VALUES ('REUNIAO 1','0808', '10H', 'ESCRITORIO 1');
INSERT INTO AGENDA (COMPROMISSO, DATE, TIME, LOCAL) VALUES ('REUNIAO 2','0808', '10H', 'ESCRITORIO 2');
INSERT INTO AGENDA (COMPROMISSO, DATE, TIME, LOCAL) VALUES ('REUNIAO 3','0808', '10H', 'ESCRITORIO 3');